import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { User } from '../types.ts';

export const generateSummaryReport = (reports: any[], filters: any, user: User | null) => {
  const doc = new jsPDF('landscape');
  const timestamp = new Date().toLocaleString();

  // Add Logo / Header
  doc.setFontSize(20);
  doc.setTextColor(40, 44, 52);
  doc.text('CDA Report Monitoring System', 14, 22);
  
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text('Compliance Summary Report', 14, 30);
  
  doc.setFontSize(9);
  doc.text(`Generated by: ${user?.displayName || 'System'} | Date: ${timestamp}`, 14, 36);
  
  if (filters) {
    let filterText = 'Filters: ';
    if (filters.region) filterText += `Region: ${filters.region} | `;
    if (filters.status) filterText += `Status: ${filters.status} | `;
    if (filters.complianceStatus) filterText += `Compliance: ${filters.complianceStatus}`;
    doc.text(filterText, 14, 42);
  }

  const tableData = reports.map(r => [
    r.cooperativeName,
    r.registrationNumber,
    r.region || 'N/A',
    r.status,
    r.complianceStatus || 'N/A',
    r.inspectionStatus || 'N/A',
    r.submissionDate ? new Date(r.submissionDate).toLocaleDateString() : 'N/A',
    r.parsedData?.["Number of days delayed"] || '0',
    `P${r.parsedData?.["Amount of penalty"] || '0.00'}`
  ]);

  autoTable(doc, {
    startY: 48,
    head: [['Cooperative Name', 'Reg #', 'Region', 'Main Status', 'Compliance', 'Inspection', 'Submitted', 'Delay', 'Penalty']],
    body: tableData,
    headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 8, cellPadding: 2 },
    margin: { top: 48 },
  });

  doc.save(`CDA_Summary_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};

export const generateEvaluationReport = (report: any, user: User | null) => {
  const doc = new jsPDF();
  const timestamp = new Date().toLocaleString();

  // Header Section
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setFontSize(22);
  doc.setTextColor(255);
  doc.text('EVALUATION REPORT', 105, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.text('Cooperative Development Authority (CDA)', 105, 28, { align: 'center' });

  // Body Content
  doc.setTextColor(40, 44, 52);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('I. COOPERATIVE IDENTITY', 14, 55);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const details = [
    ['Name:', report.cooperativeName],
    ['Registration No:', report.registrationNumber],
    ['Region:', report.region || report.parsedData?.["Region"] || 'N/A'],
    ['Province:', report.parsedData?.["Province"] || 'N/A'],
    ['City/Municipality:', report.municipality || report.parsedData?.["Municipality"] || 'N/A'],
    ['Address:', report.parsedData?.["Street"] || 'N/A'],
    ['Cooperative Type:', report.cooperativeType || report.parsedData?.["Cooperative Type"] || 'N/A'],
    ['Category:', report.parsedData?.["Category"] || 'N/A'],
  ];

  autoTable(doc, {
    startY: 60,
    body: details,
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 1.5 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 40 } },
  });

  const nextY = (doc as any).lastAutoTable.finalY + 15;
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('II. COMPLIANCE STATUS & FINDINGS', 14, nextY);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  const compliance = [
    ['Main Registry Status:', report.status || 'Pending'],
    ['Compliance Status:', report.complianceStatus || 'Pending'],
    ['Compliance Date:', report.complianceDate ? new Date(report.complianceDate).toLocaleDateString() : 'N/A'],
    ['Inspection Status:', report.inspectionStatus || 'N/A'],
    ['Date Inspected:', report.dateInspected ? new Date(report.dateInspected).toLocaleDateString() : 'N/A'],
    ['Date Issued/Rec:', report.dateIssuedRecommended ? new Date(report.dateIssuedRecommended).toLocaleDateString() : 'N/A'],
    ['Date Complied (OTC/SCO):', report.dateCompliedToOTCandSCO ? new Date(report.dateCompliedToOTCandSCO).toLocaleDateString() : 'N/A'],
    ['Delayed Days:', report.parsedData?.["Number of days delayed"] || '0'],
    ['Penalty Amount:', `P${report.parsedData?.["Amount of penalty"] || '0.00'}`],
  ];

  autoTable(doc, {
    startY: nextY + 5,
    body: compliance,
    theme: 'grid',
    headStyles: { fillColor: [51, 65, 85] },
    styles: { fontSize: 10, cellPadding: 2 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 }, 1: { cellWidth: 130 } },
  });

  // Checklist of documents
  const docChecklistY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('III. DOCUMENT CHECKLIST', 14, docChecklistY);

  const docTypes = [
    { id: 'CAPR', findingsKey: 'Summary of findings' },
    { id: 'AFS', findingsKey: 'Summary of findings_5' },
    { id: 'SAR', findingsKey: 'Summary of findings_2' },
    { id: 'PAR', findingsKey: 'Summary of findings_3' },
    { id: 'MEDCON', findingsKey: 'Summary of findings_4' },
    { id: 'SWORN STATEMENT AFFIDAVIT', findingsKey: 'Summary of findings_6' },
  ];

  const checklistData = docTypes.map(d => [
    d.id,
    report.parsedData?.[d.id] || 'N/A',
    report.parsedData?.[d.findingsKey] || 'No findings recorded'
  ]);

  autoTable(doc, {
    startY: docChecklistY + 5,
    head: [['Document', 'Status', 'Findings']],
    body: checklistData,
    theme: 'striped',
    headStyles: { fillColor: [37, 99, 235] },
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: { 
      0: { fontStyle: 'bold', cellWidth: 40 },
      1: { cellWidth: 30 },
      2: { cellWidth: 110 }
    }
  });

  const remarksY = (doc as any).lastAutoTable.finalY + 15;
  if (remarksY > 250) doc.addPage();
  const currentRemarksY = remarksY > 250 ? 20 : remarksY;

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('IV. EVALUATION REMARKS', 14, currentRemarksY);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const splitRemarks = doc.splitTextToSize(report.evaluationRemarks || 'No remarks provided.', 180);
  doc.text(splitRemarks, 14, currentRemarksY + 8);

  // Footer / Signatures
  const footerY = 260;
  doc.setDrawColor(200);
  doc.line(14, footerY, 196, footerY);
  
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(`System Generated Report | Evaluator: ${user?.displayName || 'System'} | ID: ${report._id}`, 14, footerY + 5);
  doc.text(`Generated on: ${timestamp}`, 14, footerY + 10);

  doc.save(`Evaluation_Report_${report.registrationNumber}_${new Date().toISOString().split('T')[0]}.pdf`);
};

export const generateCustomReport = (reports: any[], selectedFields: {id: string, label: string}[], filters: any, user: User | null) => {
  const doc = new jsPDF('landscape');
  const timestamp = new Date().toLocaleString();

  doc.setFontSize(18);
  doc.setTextColor(40, 44, 52);
  doc.text('CDA Custom Built Report', 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated by: ${user?.displayName || 'System'} | Date: ${timestamp}`, 14, 30);

  if (filters) {
    let filterText = 'Active Filters: ';
    if (filters.region) filterText += `Region: ${filters.region} | `;
    if (filters.status) filterText += `Status: ${filters.status} | `;
    doc.text(filterText, 14, 36);
  }

  const head = [selectedFields.map(f => f.label)];
  const body = reports.map(r => {
    return selectedFields.map(field => {
      // Map common fields or fallback to parsedData
      switch(field.id) {
        case 'cooperativeName': return r.cooperativeName;
        case 'registrationNumber': return r.registrationNumber;
        case 'region': return r.region || 'N/A';
        case 'status': return r.status;
        case 'complianceStatus': return r.complianceStatus || 'N/A';
        case 'inspectionStatus': return r.inspectionStatus || 'N/A';
        case 'submissionDate': return r.submissionDate ? new Date(r.submissionDate).toLocaleDateString() : 'N/A';
        case 'dateInspected': return r.dateInspected ? new Date(r.dateInspected).toLocaleDateString() : 'N/A';
        case 'dateIssuedRecommended': return r.dateIssuedRecommended ? new Date(r.dateIssuedRecommended).toLocaleDateString() : 'N/A';
        case 'dateCompliedToOTCandSCO': return r.dateCompliedToOTCandSCO ? new Date(r.dateCompliedToOTCandSCO).toLocaleDateString() : 'N/A';
        case 'penalty': return `P${r.parsedData?.["Amount of penalty"] || '0.00'}`;
        case 'delay': return r.parsedData?.["Number of days delayed"] || '0';
        default: return r.parsedData?.[field.id] || 'N/A';
      }
    });
  });

  autoTable(doc, {
    startY: 42,
    head: head,
    body: body,
    headStyles: { fillColor: [79, 70, 229], textColor: 255 },
    styles: { fontSize: 7, cellPadding: 1.5 },
    margin: { top: 40 },
  });

  doc.save(`CDA_Custom_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};
