export const PHILIPPINE_REGIONS = [
  { id: 'NCR', name: 'National Capital Region', code: '130000000' },
  { id: 'CAR', name: 'Cordillera Administrative Region', code: '140000000' },
  { id: 'REG_I', name: 'Region I (Ilocos Region)', code: '010000000' },
  { id: 'REG_II', name: 'Region II (Cagayan Valley)', code: '020000000' },
  { id: 'REG_III', name: 'Region III (Central Luzon)', code: '030000000' },
  { id: 'REG_IVA', name: 'Region IV-A (CALABARZON)', code: '040000000' },
  { id: 'MIMAROPA', name: 'MIMAROPA Region', code: '170000000' },
  { id: 'REG_V', name: 'Region V (Bicol Region)', code: '050000000' },
  { id: 'REG_VI', name: 'Region VI (Western Visayas)', code: '060000000' },
  { id: 'REG_VII', name: 'Region VII (Central Visayas)', code: '070000000' },
  { id: 'REG_VIII', name: 'Region VIII (Eastern Visayas)', code: '080000000' },
  { id: 'REG_IX', name: 'Region IX (Zamboanga Peninsula)', code: '090000000' },
  { id: 'REG_X', name: 'Region X (Northern Mindanao)', code: '100000000' },
  { id: 'REG_XI', name: 'Region XI (Davao Region)', code: '110000000' },
  { id: 'REG_XII', name: 'Region XII (SOCCSKSARGEN)', code: '120000000' },
  { id: 'REG_XIII', name: 'Region XIII (Caraga)', code: '160000000' },
  { id: 'NIR', name: 'Negros Island Region', code: '180000000' },
  { id: 'BARMM', name: 'Bangsamoro Autonomous Region in Muslim Mindanao', code: '190000000' },
];

export const PHILIPPINE_PROVINCES = [
  { id: 'ABRA', name: 'Abra', regionId: 'CAR' },
  { id: 'AGUSAN_DEL_NORTE', name: 'Agusan del Norte', regionId: 'REG_XIII' },
  { id: 'AGUSAN_DEL_SUR', name: 'Agusan del Sur', regionId: 'REG_XIII' },
  { id: 'AKLAN', name: 'Aklan', regionId: 'REG_VI' },
  { id: 'ALBAY', name: 'Albay', regionId: 'REG_V' },
  { id: 'ANTIQUE', name: 'Antique', regionId: 'REG_VI' },
  { id: 'APAYAO', name: 'Apayao', regionId: 'CAR' },
  { id: 'AURORA', name: 'Aurora', regionId: 'REG_III' },
  { id: 'BASILAN', name: 'Basilan', regionId: 'BARMM' },
  { id: 'BATAAN', name: 'Bataan', regionId: 'REG_III' },
  { id: 'BATANES', name: 'Batanes', regionId: 'REG_II' },
  { id: 'BATANGAS', name: 'Batangas', regionId: 'REG_IVA' },
  { id: 'BENGUET', name: 'Benguet', regionId: 'CAR' },
  { id: 'BILIRAN', name: 'Biliran', regionId: 'REG_VIII' },
  { id: 'BOHOL', name: 'Bohol', regionId: 'REG_VII' },
  { id: 'BUKIDNON', name: 'Bukidnon', regionId: 'REG_X' },
  { id: 'BULACAN', name: 'Bulacan', regionId: 'REG_III' },
  { id: 'CAGAYAN', name: 'Cagayan', regionId: 'REG_II' },
  { id: 'CAMARINES_NORTE', name: 'Camarines Norte', regionId: 'REG_V' },
  { id: 'CAMARINES_SUR', name: 'Camarines Sur', regionId: 'REG_V' },
  { id: 'CAMIGUIN', name: 'Camiguin', regionId: 'REG_X' },
  { id: 'CAPIZ', name: 'Capiz', regionId: 'REG_VI' },
  { id: 'CATANDUANES', name: 'Catanduanes', regionId: 'REG_V' },
  { id: 'CAVITE', name: 'Cavite', regionId: 'REG_IVA' },
  { id: 'CEBU', name: 'Cebu', regionId: 'REG_VII' },
  { id: 'COTABATO', name: 'Cotabato', regionId: 'REG_XII' },
  { id: 'DAVAO_DE_ORO', name: 'Davao de Oro', regionId: 'REG_XI' },
  { id: 'DAVAO_DEL_NORTE', name: 'Davao del Norte', regionId: 'REG_XI' },
  { id: 'DAVAO_DEL_SUR', name: 'Davao del Sur', regionId: 'REG_XI' },
  { id: 'DAVAO_OCCIDENTAL', name: 'Davao Occidental', regionId: 'REG_XI' },
  { id: 'DAVAO_ORIENTAL', name: 'Davao Oriental', regionId: 'REG_XI' },
  { id: 'DINAGAT_ISLANDS', name: 'Dinagat Islands', regionId: 'REG_XIII' },
  { id: 'EASTERN_SAMAR', name: 'Eastern Samar', regionId: 'REG_VIII' },
  { id: 'GUIMARAS', name: 'Guimaras', regionId: 'REG_VI' },
  { id: 'IFUGAO', name: 'Ifugao', regionId: 'CAR' },
  { id: 'ILOCOS_NORTE', name: 'Ilocos Norte', regionId: 'REG_I' },
  { id: 'ILOCOS_SUR', name: 'Ilocos Sur', regionId: 'REG_I' },
  { id: 'ILOILO', name: 'Iloilo', regionId: 'REG_VI' },
  { id: 'ISABELA', name: 'Isabela', regionId: 'REG_II' },
  { id: 'KALINGA', name: 'Kalinga', regionId: 'CAR' },
  { id: 'LA_UNION', name: 'La Union', regionId: 'REG_I' },
  { id: 'LAGUNA', name: 'Laguna', regionId: 'REG_IVA' },
  { id: 'LANAO_DEL_NORTE', name: 'Lanao del Norte', regionId: 'REG_X' },
  { id: 'LANAO_DEL_SUR', name: 'Lanao del Sur', regionId: 'BARMM' },
  { id: 'LEYTE', name: 'Leyte', regionId: 'REG_VIII' },
  { id: 'MAGUINDANAO_DEL_NORTE', name: 'Maguindanao del Norte', regionId: 'BARMM' },
  { id: 'MAGUINDANAO_DEL_SUR', name: 'Maguindanao del Sur', regionId: 'BARMM' },
  { id: 'MARINDUQUE', name: 'Marinduque', regionId: 'MIMAROPA' },
  { id: 'MASBATE', name: 'Masbate', regionId: 'REG_V' },
  { id: 'MISAMIS_OCCIDENTAL', name: 'Misamis Occidental', regionId: 'REG_X' },
  { id: 'MISAMIS_ORIENTAL', name: 'Misamis Oriental', regionId: 'REG_X' },
  { id: 'MOUNTAIN_PROVINCE', name: 'Mountain Province', regionId: 'CAR' },
  { id: 'NEGROS_OCCIDENTAL', name: 'Negros Occidental', regionId: 'NIR' },
  { id: 'NEGROS_ORIENTAL', name: 'Negros Oriental', regionId: 'NIR' },
  { id: 'NORTHERN_SAMAR', name: 'Northern Samar', regionId: 'REG_VIII' },
  { id: 'NUEVA_ECIJA', name: 'Nueva Ecija', regionId: 'REG_III' },
  { id: 'NUEVA_VIZCAYA', name: 'Nueva Vizcaya', regionId: 'REG_II' },
  { id: 'OCCIDENTAL_MINDORO', name: 'Occidental Mindoro', regionId: 'MIMAROPA' },
  { id: 'ORIENTAL_MINDORO', name: 'Oriental Mindoro', regionId: 'MIMAROPA' },
  { id: 'PALAWAN', name: 'Palawan', regionId: 'MIMAROPA' },
  { id: 'PAMPANGA', name: 'Pampanga', regionId: 'REG_III' },
  { id: 'PANGASINAN', name: 'Pangasinan', regionId: 'REG_I' },
  { id: 'QUEZON', name: 'Quezon', regionId: 'REG_IVA' },
  { id: 'QUIRINO', name: 'Quirino', regionId: 'REG_II' },
  { id: 'RIZAL', name: 'Rizal', regionId: 'REG_IVA' },
  { id: 'ROMBLON', name: 'Romblon', regionId: 'MIMAROPA' },
  { id: 'SAMAR', name: 'Samar', regionId: 'REG_VIII' },
  { id: 'SARANGANI', name: 'Sarangani', regionId: 'REG_XII' },
  { id: 'SIQUIJOR', name: 'Siquijor', regionId: 'REG_VII' },
  { id: 'SORSOGON', name: 'Sorsogon', regionId: 'REG_V' },
  { id: 'SOUTH_COTABATO', name: 'South Cotabato', regionId: 'REG_XII' },
  { id: 'SOUTHERN_LEYTE', name: 'Southern Leyte', regionId: 'REG_VIII' },
  { id: 'SULTAN_KUDARAT', name: 'Sultan Kudarat', regionId: 'REG_XII' },
  { id: 'SULU', name: 'Sulu', regionId: 'BARMM' },
  { id: 'SURIGAO_DEL_NORTE', name: 'Surigao del Norte', regionId: 'REG_XIII' },
  { id: 'SURIGAO_DEL_SUR', name: 'Surigao del Sur', regionId: 'REG_XIII' },
  { id: 'TARLAC', name: 'Tarlac', regionId: 'REG_III' },
  { id: 'TAWI_TAWI', name: 'Tawi-Tawi', regionId: 'BARMM' },
  { id: 'ZAMBALES', name: 'Zambales', regionId: 'REG_III' },
  { id: 'ZAMBOANGA_DEL_NORTE', name: 'Zamboanga del Norte', regionId: 'REG_IX' },
  { id: 'ZAMBOANGA_DEL_SUR', name: 'Zamboanga del Sur', regionId: 'REG_IX' },
  { id: 'ZAMBOANGA_SIBUGAY', name: 'Zamboanga Sibugay', regionId: 'REG_IX' },
];

export const UserRole = {
  ADMIN: 'Admin',
  ANALYST: 'Central Office Evaluator',
  REGIONAL_ANALYST: 'Regional Office Evaluator',
  VIEWER: 'Viewer',
} as const;

export type UserRole = typeof UserRole[keyof typeof UserRole];
